name: reels_demo
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  video_player: ^2.9.3
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/
