name: reels_demo
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  audioplayers: ^6.3.0
  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/i-jared/ffmpeg_kit_flutter
      ref: main
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  http: ^1.3.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  skeletonizer: ^1.4.3
  video_player: ^2.9.3
  visibility_detector: ^0.4.0+2
  whitecodel_reels:
    path: packages/whitecodel_reels

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/
